package cn.uestc.hotel.mapper;

import cn.uestc.hotel.domain.Hotel;
import cn.uestc.hotel.domain.HotelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelMapper extends HotelMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jul 31 14:02:19 CST 2019
     */
    long countByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jul 31 14:02:19 CST 2019
     */
    int deleteByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jul 31 14:02:19 CST 2019
     */
    int deleteByPrimaryKey(String hotelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jul 31 14:02:19 CST 2019
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jul 31 14:02:19 CST 2019
     */
    int insertSelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jul 31 14:02:19 CST 2019
     */
    List<Hotel> selectByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jul 31 14:02:19 CST 2019
     */
    Hotel selectByPrimaryKey(String hotelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jul 31 14:02:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jul 31 14:02:19 CST 2019
     */
    int updateByExample(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jul 31 14:02:19 CST 2019
     */
    int updateByPrimaryKeySelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jul 31 14:02:19 CST 2019
     */
    int updateByPrimaryKey(Hotel record);
}