package cn.uestc.hotel.mapper;

import cn.uestc.hotel.domain.Hotel;
import cn.uestc.hotel.domain.HotelExample;
import cn.uestc.hotel.domain.HotelWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelMapper extends HotelMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    long countByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    int deleteByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    int deleteByPrimaryKey(String hotelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    int insert(HotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    int insertSelective(HotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    List<HotelWithBLOBs> selectByExampleWithBLOBs(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    List<Hotel> selectByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    HotelWithBLOBs selectByPrimaryKey(String hotelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") HotelWithBLOBs record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") HotelWithBLOBs record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    int updateByExample(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    int updateByPrimaryKeySelective(HotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(HotelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sat Aug 03 09:37:16 CST 2019
     */
    int updateByPrimaryKey(Hotel record);
}