package cn.uestc.hotel.domain;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CID
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.RID
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    private String rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Cpassword
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    private String cpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Cname
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Sex
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Phone
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public Customer(String cid, String rid, String cpassword, String cname, String sex, String phone) {
        this.cid = cid;
        this.rid = rid;
        this.cpassword = cpassword;
        this.cname = cname;
        this.sex = sex;
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public Customer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CID
     *
     * @return the value of customer.CID
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CID
     *
     * @param cid the value for customer.CID
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.RID
     *
     * @return the value of customer.RID
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.RID
     *
     * @param rid the value for customer.RID
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public void setRid(String rid) {
        this.rid = rid == null ? null : rid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Cpassword
     *
     * @return the value of customer.Cpassword
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public String getCpassword() {
        return cpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Cpassword
     *
     * @param cpassword the value for customer.Cpassword
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public void setCpassword(String cpassword) {
        this.cpassword = cpassword == null ? null : cpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Cname
     *
     * @return the value of customer.Cname
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Cname
     *
     * @param cname the value for customer.Cname
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Sex
     *
     * @return the value of customer.Sex
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Sex
     *
     * @param sex the value for customer.Sex
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Phone
     *
     * @return the value of customer.Phone
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Phone
     *
     * @param phone the value for customer.Phone
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Customer other = (Customer) that;
        return (this.getCid() == null ? other.getCid() == null : this.getCid().equals(other.getCid()))
            && (this.getRid() == null ? other.getRid() == null : this.getRid().equals(other.getRid()))
            && (this.getCpassword() == null ? other.getCpassword() == null : this.getCpassword().equals(other.getCpassword()))
            && (this.getCname() == null ? other.getCname() == null : this.getCname().equals(other.getCname()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Tue Jul 23 10:46:47 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
        result = prime * result + ((getRid() == null) ? 0 : getRid().hashCode());
        result = prime * result + ((getCpassword() == null) ? 0 : getCpassword().hashCode());
        result = prime * result + ((getCname() == null) ? 0 : getCname().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        return result;
    }
}