package cn.uestc.hotel.domain;

import java.util.ArrayList;
import java.util.List;

public class HotelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    public HotelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHotelidIsNull() {
            addCriterion("HotelID is null");
            return (Criteria) this;
        }

        public Criteria andHotelidIsNotNull() {
            addCriterion("HotelID is not null");
            return (Criteria) this;
        }

        public Criteria andHotelidEqualTo(String value) {
            addCriterion("HotelID =", value, "hotelid");
            return (Criteria) this;
        }

        public Criteria andHotelidNotEqualTo(String value) {
            addCriterion("HotelID <>", value, "hotelid");
            return (Criteria) this;
        }

        public Criteria andHotelidGreaterThan(String value) {
            addCriterion("HotelID >", value, "hotelid");
            return (Criteria) this;
        }

        public Criteria andHotelidGreaterThanOrEqualTo(String value) {
            addCriterion("HotelID >=", value, "hotelid");
            return (Criteria) this;
        }

        public Criteria andHotelidLessThan(String value) {
            addCriterion("HotelID <", value, "hotelid");
            return (Criteria) this;
        }

        public Criteria andHotelidLessThanOrEqualTo(String value) {
            addCriterion("HotelID <=", value, "hotelid");
            return (Criteria) this;
        }

        public Criteria andHotelidLike(String value) {
            addCriterion("HotelID like", value, "hotelid");
            return (Criteria) this;
        }

        public Criteria andHotelidNotLike(String value) {
            addCriterion("HotelID not like", value, "hotelid");
            return (Criteria) this;
        }

        public Criteria andHotelidIn(List<String> values) {
            addCriterion("HotelID in", values, "hotelid");
            return (Criteria) this;
        }

        public Criteria andHotelidNotIn(List<String> values) {
            addCriterion("HotelID not in", values, "hotelid");
            return (Criteria) this;
        }

        public Criteria andHotelidBetween(String value1, String value2) {
            addCriterion("HotelID between", value1, value2, "hotelid");
            return (Criteria) this;
        }

        public Criteria andHotelidNotBetween(String value1, String value2) {
            addCriterion("HotelID not between", value1, value2, "hotelid");
            return (Criteria) this;
        }

        public Criteria andHotelnameIsNull() {
            addCriterion("HotelName is null");
            return (Criteria) this;
        }

        public Criteria andHotelnameIsNotNull() {
            addCriterion("HotelName is not null");
            return (Criteria) this;
        }

        public Criteria andHotelnameEqualTo(String value) {
            addCriterion("HotelName =", value, "hotelname");
            return (Criteria) this;
        }

        public Criteria andHotelnameNotEqualTo(String value) {
            addCriterion("HotelName <>", value, "hotelname");
            return (Criteria) this;
        }

        public Criteria andHotelnameGreaterThan(String value) {
            addCriterion("HotelName >", value, "hotelname");
            return (Criteria) this;
        }

        public Criteria andHotelnameGreaterThanOrEqualTo(String value) {
            addCriterion("HotelName >=", value, "hotelname");
            return (Criteria) this;
        }

        public Criteria andHotelnameLessThan(String value) {
            addCriterion("HotelName <", value, "hotelname");
            return (Criteria) this;
        }

        public Criteria andHotelnameLessThanOrEqualTo(String value) {
            addCriterion("HotelName <=", value, "hotelname");
            return (Criteria) this;
        }

        public Criteria andHotelnameLike(String value) {
            addCriterion("HotelName like", value, "hotelname");
            return (Criteria) this;
        }

        public Criteria andHotelnameNotLike(String value) {
            addCriterion("HotelName not like", value, "hotelname");
            return (Criteria) this;
        }

        public Criteria andHotelnameIn(List<String> values) {
            addCriterion("HotelName in", values, "hotelname");
            return (Criteria) this;
        }

        public Criteria andHotelnameNotIn(List<String> values) {
            addCriterion("HotelName not in", values, "hotelname");
            return (Criteria) this;
        }

        public Criteria andHotelnameBetween(String value1, String value2) {
            addCriterion("HotelName between", value1, value2, "hotelname");
            return (Criteria) this;
        }

        public Criteria andHotelnameNotBetween(String value1, String value2) {
            addCriterion("HotelName not between", value1, value2, "hotelname");
            return (Criteria) this;
        }

        public Criteria andNumroomIsNull() {
            addCriterion("NumRoom is null");
            return (Criteria) this;
        }

        public Criteria andNumroomIsNotNull() {
            addCriterion("NumRoom is not null");
            return (Criteria) this;
        }

        public Criteria andNumroomEqualTo(Integer value) {
            addCriterion("NumRoom =", value, "numroom");
            return (Criteria) this;
        }

        public Criteria andNumroomNotEqualTo(Integer value) {
            addCriterion("NumRoom <>", value, "numroom");
            return (Criteria) this;
        }

        public Criteria andNumroomGreaterThan(Integer value) {
            addCriterion("NumRoom >", value, "numroom");
            return (Criteria) this;
        }

        public Criteria andNumroomGreaterThanOrEqualTo(Integer value) {
            addCriterion("NumRoom >=", value, "numroom");
            return (Criteria) this;
        }

        public Criteria andNumroomLessThan(Integer value) {
            addCriterion("NumRoom <", value, "numroom");
            return (Criteria) this;
        }

        public Criteria andNumroomLessThanOrEqualTo(Integer value) {
            addCriterion("NumRoom <=", value, "numroom");
            return (Criteria) this;
        }

        public Criteria andNumroomIn(List<Integer> values) {
            addCriterion("NumRoom in", values, "numroom");
            return (Criteria) this;
        }

        public Criteria andNumroomNotIn(List<Integer> values) {
            addCriterion("NumRoom not in", values, "numroom");
            return (Criteria) this;
        }

        public Criteria andNumroomBetween(Integer value1, Integer value2) {
            addCriterion("NumRoom between", value1, value2, "numroom");
            return (Criteria) this;
        }

        public Criteria andNumroomNotBetween(Integer value1, Integer value2) {
            addCriterion("NumRoom not between", value1, value2, "numroom");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("Address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("Address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("Address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("Address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("Address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("Address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("Address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("Address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("Address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("Address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("Address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("Address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("Address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("Address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andEnglishnameIsNull() {
            addCriterion("EnglishName is null");
            return (Criteria) this;
        }

        public Criteria andEnglishnameIsNotNull() {
            addCriterion("EnglishName is not null");
            return (Criteria) this;
        }

        public Criteria andEnglishnameEqualTo(String value) {
            addCriterion("EnglishName =", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameNotEqualTo(String value) {
            addCriterion("EnglishName <>", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameGreaterThan(String value) {
            addCriterion("EnglishName >", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameGreaterThanOrEqualTo(String value) {
            addCriterion("EnglishName >=", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameLessThan(String value) {
            addCriterion("EnglishName <", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameLessThanOrEqualTo(String value) {
            addCriterion("EnglishName <=", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameLike(String value) {
            addCriterion("EnglishName like", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameNotLike(String value) {
            addCriterion("EnglishName not like", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameIn(List<String> values) {
            addCriterion("EnglishName in", values, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameNotIn(List<String> values) {
            addCriterion("EnglishName not in", values, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameBetween(String value1, String value2) {
            addCriterion("EnglishName between", value1, value2, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameNotBetween(String value1, String value2) {
            addCriterion("EnglishName not between", value1, value2, "englishname");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("Country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("Country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("Country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("Country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("Country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("Country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("Country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("Country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("Country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("Country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("Country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("Country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("Country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("Country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("City is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("City is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("City =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("City <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("City >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("City >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("City <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("City <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("City like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("City not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("City in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("City not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("City between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("City not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("Url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("Url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("Url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("Url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("Url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("Url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("Url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("Url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("Url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("Url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("Url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("Url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("Url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("Url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("Tel is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("Tel is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("Tel =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("Tel <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("Tel >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("Tel >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("Tel <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("Tel <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("Tel like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("Tel not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("Tel in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("Tel not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("Tel between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("Tel not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andZipcodeIsNull() {
            addCriterion("Zipcode is null");
            return (Criteria) this;
        }

        public Criteria andZipcodeIsNotNull() {
            addCriterion("Zipcode is not null");
            return (Criteria) this;
        }

        public Criteria andZipcodeEqualTo(String value) {
            addCriterion("Zipcode =", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotEqualTo(String value) {
            addCriterion("Zipcode <>", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeGreaterThan(String value) {
            addCriterion("Zipcode >", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeGreaterThanOrEqualTo(String value) {
            addCriterion("Zipcode >=", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLessThan(String value) {
            addCriterion("Zipcode <", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLessThanOrEqualTo(String value) {
            addCriterion("Zipcode <=", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLike(String value) {
            addCriterion("Zipcode like", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotLike(String value) {
            addCriterion("Zipcode not like", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeIn(List<String> values) {
            addCriterion("Zipcode in", values, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotIn(List<String> values) {
            addCriterion("Zipcode not in", values, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeBetween(String value1, String value2) {
            addCriterion("Zipcode between", value1, value2, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotBetween(String value1, String value2) {
            addCriterion("Zipcode not between", value1, value2, "zipcode");
            return (Criteria) this;
        }

        public Criteria andIsavailableIsNull() {
            addCriterion("IsAvailable is null");
            return (Criteria) this;
        }

        public Criteria andIsavailableIsNotNull() {
            addCriterion("IsAvailable is not null");
            return (Criteria) this;
        }

        public Criteria andIsavailableEqualTo(Integer value) {
            addCriterion("IsAvailable =", value, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableNotEqualTo(Integer value) {
            addCriterion("IsAvailable <>", value, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableGreaterThan(Integer value) {
            addCriterion("IsAvailable >", value, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableGreaterThanOrEqualTo(Integer value) {
            addCriterion("IsAvailable >=", value, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableLessThan(Integer value) {
            addCriterion("IsAvailable <", value, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableLessThanOrEqualTo(Integer value) {
            addCriterion("IsAvailable <=", value, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableIn(List<Integer> values) {
            addCriterion("IsAvailable in", values, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableNotIn(List<Integer> values) {
            addCriterion("IsAvailable not in", values, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableBetween(Integer value1, Integer value2) {
            addCriterion("IsAvailable between", value1, value2, "isavailable");
            return (Criteria) this;
        }

        public Criteria andIsavailableNotBetween(Integer value1, Integer value2) {
            addCriterion("IsAvailable not between", value1, value2, "isavailable");
            return (Criteria) this;
        }

        public Criteria andRoomtype2IsNull() {
            addCriterion("RoomType2 is null");
            return (Criteria) this;
        }

        public Criteria andRoomtype2IsNotNull() {
            addCriterion("RoomType2 is not null");
            return (Criteria) this;
        }

        public Criteria andRoomtype2EqualTo(String value) {
            addCriterion("RoomType2 =", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2NotEqualTo(String value) {
            addCriterion("RoomType2 <>", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2GreaterThan(String value) {
            addCriterion("RoomType2 >", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2GreaterThanOrEqualTo(String value) {
            addCriterion("RoomType2 >=", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2LessThan(String value) {
            addCriterion("RoomType2 <", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2LessThanOrEqualTo(String value) {
            addCriterion("RoomType2 <=", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2Like(String value) {
            addCriterion("RoomType2 like", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2NotLike(String value) {
            addCriterion("RoomType2 not like", value, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2In(List<String> values) {
            addCriterion("RoomType2 in", values, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2NotIn(List<String> values) {
            addCriterion("RoomType2 not in", values, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2Between(String value1, String value2) {
            addCriterion("RoomType2 between", value1, value2, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andRoomtype2NotBetween(String value1, String value2) {
            addCriterion("RoomType2 not between", value1, value2, "roomtype2");
            return (Criteria) this;
        }

        public Criteria andImgnameIsNull() {
            addCriterion("ImgName is null");
            return (Criteria) this;
        }

        public Criteria andImgnameIsNotNull() {
            addCriterion("ImgName is not null");
            return (Criteria) this;
        }

        public Criteria andImgnameEqualTo(String value) {
            addCriterion("ImgName =", value, "imgname");
            return (Criteria) this;
        }

        public Criteria andImgnameNotEqualTo(String value) {
            addCriterion("ImgName <>", value, "imgname");
            return (Criteria) this;
        }

        public Criteria andImgnameGreaterThan(String value) {
            addCriterion("ImgName >", value, "imgname");
            return (Criteria) this;
        }

        public Criteria andImgnameGreaterThanOrEqualTo(String value) {
            addCriterion("ImgName >=", value, "imgname");
            return (Criteria) this;
        }

        public Criteria andImgnameLessThan(String value) {
            addCriterion("ImgName <", value, "imgname");
            return (Criteria) this;
        }

        public Criteria andImgnameLessThanOrEqualTo(String value) {
            addCriterion("ImgName <=", value, "imgname");
            return (Criteria) this;
        }

        public Criteria andImgnameLike(String value) {
            addCriterion("ImgName like", value, "imgname");
            return (Criteria) this;
        }

        public Criteria andImgnameNotLike(String value) {
            addCriterion("ImgName not like", value, "imgname");
            return (Criteria) this;
        }

        public Criteria andImgnameIn(List<String> values) {
            addCriterion("ImgName in", values, "imgname");
            return (Criteria) this;
        }

        public Criteria andImgnameNotIn(List<String> values) {
            addCriterion("ImgName not in", values, "imgname");
            return (Criteria) this;
        }

        public Criteria andImgnameBetween(String value1, String value2) {
            addCriterion("ImgName between", value1, value2, "imgname");
            return (Criteria) this;
        }

        public Criteria andImgnameNotBetween(String value1, String value2) {
            addCriterion("ImgName not between", value1, value2, "imgname");
            return (Criteria) this;
        }

        public Criteria andHotelclassIsNull() {
            addCriterion("HotelClass is null");
            return (Criteria) this;
        }

        public Criteria andHotelclassIsNotNull() {
            addCriterion("HotelClass is not null");
            return (Criteria) this;
        }

        public Criteria andHotelclassEqualTo(String value) {
            addCriterion("HotelClass =", value, "hotelclass");
            return (Criteria) this;
        }

        public Criteria andHotelclassNotEqualTo(String value) {
            addCriterion("HotelClass <>", value, "hotelclass");
            return (Criteria) this;
        }

        public Criteria andHotelclassGreaterThan(String value) {
            addCriterion("HotelClass >", value, "hotelclass");
            return (Criteria) this;
        }

        public Criteria andHotelclassGreaterThanOrEqualTo(String value) {
            addCriterion("HotelClass >=", value, "hotelclass");
            return (Criteria) this;
        }

        public Criteria andHotelclassLessThan(String value) {
            addCriterion("HotelClass <", value, "hotelclass");
            return (Criteria) this;
        }

        public Criteria andHotelclassLessThanOrEqualTo(String value) {
            addCriterion("HotelClass <=", value, "hotelclass");
            return (Criteria) this;
        }

        public Criteria andHotelclassLike(String value) {
            addCriterion("HotelClass like", value, "hotelclass");
            return (Criteria) this;
        }

        public Criteria andHotelclassNotLike(String value) {
            addCriterion("HotelClass not like", value, "hotelclass");
            return (Criteria) this;
        }

        public Criteria andHotelclassIn(List<String> values) {
            addCriterion("HotelClass in", values, "hotelclass");
            return (Criteria) this;
        }

        public Criteria andHotelclassNotIn(List<String> values) {
            addCriterion("HotelClass not in", values, "hotelclass");
            return (Criteria) this;
        }

        public Criteria andHotelclassBetween(String value1, String value2) {
            addCriterion("HotelClass between", value1, value2, "hotelclass");
            return (Criteria) this;
        }

        public Criteria andHotelclassNotBetween(String value1, String value2) {
            addCriterion("HotelClass not between", value1, value2, "hotelclass");
            return (Criteria) this;
        }

        public Criteria andRoomtype1IsNull() {
            addCriterion("RoomType1 is null");
            return (Criteria) this;
        }

        public Criteria andRoomtype1IsNotNull() {
            addCriterion("RoomType1 is not null");
            return (Criteria) this;
        }

        public Criteria andRoomtype1EqualTo(String value) {
            addCriterion("RoomType1 =", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1NotEqualTo(String value) {
            addCriterion("RoomType1 <>", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1GreaterThan(String value) {
            addCriterion("RoomType1 >", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1GreaterThanOrEqualTo(String value) {
            addCriterion("RoomType1 >=", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1LessThan(String value) {
            addCriterion("RoomType1 <", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1LessThanOrEqualTo(String value) {
            addCriterion("RoomType1 <=", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1Like(String value) {
            addCriterion("RoomType1 like", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1NotLike(String value) {
            addCriterion("RoomType1 not like", value, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1In(List<String> values) {
            addCriterion("RoomType1 in", values, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1NotIn(List<String> values) {
            addCriterion("RoomType1 not in", values, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1Between(String value1, String value2) {
            addCriterion("RoomType1 between", value1, value2, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype1NotBetween(String value1, String value2) {
            addCriterion("RoomType1 not between", value1, value2, "roomtype1");
            return (Criteria) this;
        }

        public Criteria andRoomtype3IsNull() {
            addCriterion("RoomType3 is null");
            return (Criteria) this;
        }

        public Criteria andRoomtype3IsNotNull() {
            addCriterion("RoomType3 is not null");
            return (Criteria) this;
        }

        public Criteria andRoomtype3EqualTo(String value) {
            addCriterion("RoomType3 =", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3NotEqualTo(String value) {
            addCriterion("RoomType3 <>", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3GreaterThan(String value) {
            addCriterion("RoomType3 >", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3GreaterThanOrEqualTo(String value) {
            addCriterion("RoomType3 >=", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3LessThan(String value) {
            addCriterion("RoomType3 <", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3LessThanOrEqualTo(String value) {
            addCriterion("RoomType3 <=", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3Like(String value) {
            addCriterion("RoomType3 like", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3NotLike(String value) {
            addCriterion("RoomType3 not like", value, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3In(List<String> values) {
            addCriterion("RoomType3 in", values, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3NotIn(List<String> values) {
            addCriterion("RoomType3 not in", values, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3Between(String value1, String value2) {
            addCriterion("RoomType3 between", value1, value2, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype3NotBetween(String value1, String value2) {
            addCriterion("RoomType3 not between", value1, value2, "roomtype3");
            return (Criteria) this;
        }

        public Criteria andRoomtype4IsNull() {
            addCriterion("RoomType4 is null");
            return (Criteria) this;
        }

        public Criteria andRoomtype4IsNotNull() {
            addCriterion("RoomType4 is not null");
            return (Criteria) this;
        }

        public Criteria andRoomtype4EqualTo(String value) {
            addCriterion("RoomType4 =", value, "roomtype4");
            return (Criteria) this;
        }

        public Criteria andRoomtype4NotEqualTo(String value) {
            addCriterion("RoomType4 <>", value, "roomtype4");
            return (Criteria) this;
        }

        public Criteria andRoomtype4GreaterThan(String value) {
            addCriterion("RoomType4 >", value, "roomtype4");
            return (Criteria) this;
        }

        public Criteria andRoomtype4GreaterThanOrEqualTo(String value) {
            addCriterion("RoomType4 >=", value, "roomtype4");
            return (Criteria) this;
        }

        public Criteria andRoomtype4LessThan(String value) {
            addCriterion("RoomType4 <", value, "roomtype4");
            return (Criteria) this;
        }

        public Criteria andRoomtype4LessThanOrEqualTo(String value) {
            addCriterion("RoomType4 <=", value, "roomtype4");
            return (Criteria) this;
        }

        public Criteria andRoomtype4Like(String value) {
            addCriterion("RoomType4 like", value, "roomtype4");
            return (Criteria) this;
        }

        public Criteria andRoomtype4NotLike(String value) {
            addCriterion("RoomType4 not like", value, "roomtype4");
            return (Criteria) this;
        }

        public Criteria andRoomtype4In(List<String> values) {
            addCriterion("RoomType4 in", values, "roomtype4");
            return (Criteria) this;
        }

        public Criteria andRoomtype4NotIn(List<String> values) {
            addCriterion("RoomType4 not in", values, "roomtype4");
            return (Criteria) this;
        }

        public Criteria andRoomtype4Between(String value1, String value2) {
            addCriterion("RoomType4 between", value1, value2, "roomtype4");
            return (Criteria) this;
        }

        public Criteria andRoomtype4NotBetween(String value1, String value2) {
            addCriterion("RoomType4 not between", value1, value2, "roomtype4");
            return (Criteria) this;
        }

        public Criteria andRoomtype5IsNull() {
            addCriterion("RoomType5 is null");
            return (Criteria) this;
        }

        public Criteria andRoomtype5IsNotNull() {
            addCriterion("RoomType5 is not null");
            return (Criteria) this;
        }

        public Criteria andRoomtype5EqualTo(String value) {
            addCriterion("RoomType5 =", value, "roomtype5");
            return (Criteria) this;
        }

        public Criteria andRoomtype5NotEqualTo(String value) {
            addCriterion("RoomType5 <>", value, "roomtype5");
            return (Criteria) this;
        }

        public Criteria andRoomtype5GreaterThan(String value) {
            addCriterion("RoomType5 >", value, "roomtype5");
            return (Criteria) this;
        }

        public Criteria andRoomtype5GreaterThanOrEqualTo(String value) {
            addCriterion("RoomType5 >=", value, "roomtype5");
            return (Criteria) this;
        }

        public Criteria andRoomtype5LessThan(String value) {
            addCriterion("RoomType5 <", value, "roomtype5");
            return (Criteria) this;
        }

        public Criteria andRoomtype5LessThanOrEqualTo(String value) {
            addCriterion("RoomType5 <=", value, "roomtype5");
            return (Criteria) this;
        }

        public Criteria andRoomtype5Like(String value) {
            addCriterion("RoomType5 like", value, "roomtype5");
            return (Criteria) this;
        }

        public Criteria andRoomtype5NotLike(String value) {
            addCriterion("RoomType5 not like", value, "roomtype5");
            return (Criteria) this;
        }

        public Criteria andRoomtype5In(List<String> values) {
            addCriterion("RoomType5 in", values, "roomtype5");
            return (Criteria) this;
        }

        public Criteria andRoomtype5NotIn(List<String> values) {
            addCriterion("RoomType5 not in", values, "roomtype5");
            return (Criteria) this;
        }

        public Criteria andRoomtype5Between(String value1, String value2) {
            addCriterion("RoomType5 between", value1, value2, "roomtype5");
            return (Criteria) this;
        }

        public Criteria andRoomtype5NotBetween(String value1, String value2) {
            addCriterion("RoomType5 not between", value1, value2, "roomtype5");
            return (Criteria) this;
        }

        public Criteria andImgtypeIsNull() {
            addCriterion("ImgType is null");
            return (Criteria) this;
        }

        public Criteria andImgtypeIsNotNull() {
            addCriterion("ImgType is not null");
            return (Criteria) this;
        }

        public Criteria andImgtypeEqualTo(String value) {
            addCriterion("ImgType =", value, "imgtype");
            return (Criteria) this;
        }

        public Criteria andImgtypeNotEqualTo(String value) {
            addCriterion("ImgType <>", value, "imgtype");
            return (Criteria) this;
        }

        public Criteria andImgtypeGreaterThan(String value) {
            addCriterion("ImgType >", value, "imgtype");
            return (Criteria) this;
        }

        public Criteria andImgtypeGreaterThanOrEqualTo(String value) {
            addCriterion("ImgType >=", value, "imgtype");
            return (Criteria) this;
        }

        public Criteria andImgtypeLessThan(String value) {
            addCriterion("ImgType <", value, "imgtype");
            return (Criteria) this;
        }

        public Criteria andImgtypeLessThanOrEqualTo(String value) {
            addCriterion("ImgType <=", value, "imgtype");
            return (Criteria) this;
        }

        public Criteria andImgtypeLike(String value) {
            addCriterion("ImgType like", value, "imgtype");
            return (Criteria) this;
        }

        public Criteria andImgtypeNotLike(String value) {
            addCriterion("ImgType not like", value, "imgtype");
            return (Criteria) this;
        }

        public Criteria andImgtypeIn(List<String> values) {
            addCriterion("ImgType in", values, "imgtype");
            return (Criteria) this;
        }

        public Criteria andImgtypeNotIn(List<String> values) {
            addCriterion("ImgType not in", values, "imgtype");
            return (Criteria) this;
        }

        public Criteria andImgtypeBetween(String value1, String value2) {
            addCriterion("ImgType between", value1, value2, "imgtype");
            return (Criteria) this;
        }

        public Criteria andImgtypeNotBetween(String value1, String value2) {
            addCriterion("ImgType not between", value1, value2, "imgtype");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1IsNull() {
            addCriterion("TypeImgName1 is null");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1IsNotNull() {
            addCriterion("TypeImgName1 is not null");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1EqualTo(String value) {
            addCriterion("TypeImgName1 =", value, "typeimgname1");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1NotEqualTo(String value) {
            addCriterion("TypeImgName1 <>", value, "typeimgname1");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1GreaterThan(String value) {
            addCriterion("TypeImgName1 >", value, "typeimgname1");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1GreaterThanOrEqualTo(String value) {
            addCriterion("TypeImgName1 >=", value, "typeimgname1");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1LessThan(String value) {
            addCriterion("TypeImgName1 <", value, "typeimgname1");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1LessThanOrEqualTo(String value) {
            addCriterion("TypeImgName1 <=", value, "typeimgname1");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1Like(String value) {
            addCriterion("TypeImgName1 like", value, "typeimgname1");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1NotLike(String value) {
            addCriterion("TypeImgName1 not like", value, "typeimgname1");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1In(List<String> values) {
            addCriterion("TypeImgName1 in", values, "typeimgname1");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1NotIn(List<String> values) {
            addCriterion("TypeImgName1 not in", values, "typeimgname1");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1Between(String value1, String value2) {
            addCriterion("TypeImgName1 between", value1, value2, "typeimgname1");
            return (Criteria) this;
        }

        public Criteria andTypeimgname1NotBetween(String value1, String value2) {
            addCriterion("TypeImgName1 not between", value1, value2, "typeimgname1");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2IsNull() {
            addCriterion("TypeImgName2 is null");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2IsNotNull() {
            addCriterion("TypeImgName2 is not null");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2EqualTo(String value) {
            addCriterion("TypeImgName2 =", value, "typeimgname2");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2NotEqualTo(String value) {
            addCriterion("TypeImgName2 <>", value, "typeimgname2");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2GreaterThan(String value) {
            addCriterion("TypeImgName2 >", value, "typeimgname2");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2GreaterThanOrEqualTo(String value) {
            addCriterion("TypeImgName2 >=", value, "typeimgname2");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2LessThan(String value) {
            addCriterion("TypeImgName2 <", value, "typeimgname2");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2LessThanOrEqualTo(String value) {
            addCriterion("TypeImgName2 <=", value, "typeimgname2");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2Like(String value) {
            addCriterion("TypeImgName2 like", value, "typeimgname2");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2NotLike(String value) {
            addCriterion("TypeImgName2 not like", value, "typeimgname2");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2In(List<String> values) {
            addCriterion("TypeImgName2 in", values, "typeimgname2");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2NotIn(List<String> values) {
            addCriterion("TypeImgName2 not in", values, "typeimgname2");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2Between(String value1, String value2) {
            addCriterion("TypeImgName2 between", value1, value2, "typeimgname2");
            return (Criteria) this;
        }

        public Criteria andTypeimgname2NotBetween(String value1, String value2) {
            addCriterion("TypeImgName2 not between", value1, value2, "typeimgname2");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3IsNull() {
            addCriterion("TypeImgName3 is null");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3IsNotNull() {
            addCriterion("TypeImgName3 is not null");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3EqualTo(String value) {
            addCriterion("TypeImgName3 =", value, "typeimgname3");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3NotEqualTo(String value) {
            addCriterion("TypeImgName3 <>", value, "typeimgname3");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3GreaterThan(String value) {
            addCriterion("TypeImgName3 >", value, "typeimgname3");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3GreaterThanOrEqualTo(String value) {
            addCriterion("TypeImgName3 >=", value, "typeimgname3");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3LessThan(String value) {
            addCriterion("TypeImgName3 <", value, "typeimgname3");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3LessThanOrEqualTo(String value) {
            addCriterion("TypeImgName3 <=", value, "typeimgname3");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3Like(String value) {
            addCriterion("TypeImgName3 like", value, "typeimgname3");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3NotLike(String value) {
            addCriterion("TypeImgName3 not like", value, "typeimgname3");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3In(List<String> values) {
            addCriterion("TypeImgName3 in", values, "typeimgname3");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3NotIn(List<String> values) {
            addCriterion("TypeImgName3 not in", values, "typeimgname3");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3Between(String value1, String value2) {
            addCriterion("TypeImgName3 between", value1, value2, "typeimgname3");
            return (Criteria) this;
        }

        public Criteria andTypeimgname3NotBetween(String value1, String value2) {
            addCriterion("TypeImgName3 not between", value1, value2, "typeimgname3");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4IsNull() {
            addCriterion("TypeImgName4 is null");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4IsNotNull() {
            addCriterion("TypeImgName4 is not null");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4EqualTo(String value) {
            addCriterion("TypeImgName4 =", value, "typeimgname4");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4NotEqualTo(String value) {
            addCriterion("TypeImgName4 <>", value, "typeimgname4");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4GreaterThan(String value) {
            addCriterion("TypeImgName4 >", value, "typeimgname4");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4GreaterThanOrEqualTo(String value) {
            addCriterion("TypeImgName4 >=", value, "typeimgname4");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4LessThan(String value) {
            addCriterion("TypeImgName4 <", value, "typeimgname4");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4LessThanOrEqualTo(String value) {
            addCriterion("TypeImgName4 <=", value, "typeimgname4");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4Like(String value) {
            addCriterion("TypeImgName4 like", value, "typeimgname4");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4NotLike(String value) {
            addCriterion("TypeImgName4 not like", value, "typeimgname4");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4In(List<String> values) {
            addCriterion("TypeImgName4 in", values, "typeimgname4");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4NotIn(List<String> values) {
            addCriterion("TypeImgName4 not in", values, "typeimgname4");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4Between(String value1, String value2) {
            addCriterion("TypeImgName4 between", value1, value2, "typeimgname4");
            return (Criteria) this;
        }

        public Criteria andTypeimgname4NotBetween(String value1, String value2) {
            addCriterion("TypeImgName4 not between", value1, value2, "typeimgname4");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5IsNull() {
            addCriterion("TypeImgName5 is null");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5IsNotNull() {
            addCriterion("TypeImgName5 is not null");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5EqualTo(String value) {
            addCriterion("TypeImgName5 =", value, "typeimgname5");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5NotEqualTo(String value) {
            addCriterion("TypeImgName5 <>", value, "typeimgname5");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5GreaterThan(String value) {
            addCriterion("TypeImgName5 >", value, "typeimgname5");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5GreaterThanOrEqualTo(String value) {
            addCriterion("TypeImgName5 >=", value, "typeimgname5");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5LessThan(String value) {
            addCriterion("TypeImgName5 <", value, "typeimgname5");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5LessThanOrEqualTo(String value) {
            addCriterion("TypeImgName5 <=", value, "typeimgname5");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5Like(String value) {
            addCriterion("TypeImgName5 like", value, "typeimgname5");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5NotLike(String value) {
            addCriterion("TypeImgName5 not like", value, "typeimgname5");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5In(List<String> values) {
            addCriterion("TypeImgName5 in", values, "typeimgname5");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5NotIn(List<String> values) {
            addCriterion("TypeImgName5 not in", values, "typeimgname5");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5Between(String value1, String value2) {
            addCriterion("TypeImgName5 between", value1, value2, "typeimgname5");
            return (Criteria) this;
        }

        public Criteria andTypeimgname5NotBetween(String value1, String value2) {
            addCriterion("TypeImgName5 not between", value1, value2, "typeimgname5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 04 10:53:13 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel
     *
     * @mbg.generated Sun Aug 04 10:53:13 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}